def from_int8(value: int) -> bytes: ...
def to_int8(value: bytes) -> int: ...
def from_uint8(value: int) -> bytes: ...
def to_uint8(value: bytes) -> int: ...

def from_int16(value: int) -> bytes: ...
def to_int16(value: bytes) -> int: ...
def from_uint16(value: int) -> bytes: ...
def to_uint16(value: bytes) -> int: ...

def from_int32(value: int) -> bytes: ...
def to_int32(value: bytes) -> int: ...
def from_uint32(value: int) -> bytes: ...
def to_uint32(value: bytes) -> int: ...

def from_int64(value: int) -> bytes: ...
def to_int64(value: bytes) -> int: ...
def from_uint64(value: int) -> bytes: ...
def to_uint64(value: bytes) -> int: ...

def from_float32(value: float) -> bytes: ...
def to_float32(value: bytes) -> float: ...
def from_float64(value: float) -> bytes: ...
def to_float64(value: bytes) -> float: ...
